### ISSUE TITLE
Support for multiple source dir/files in blackbox

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/syslog-release#38]
I would like to add agent (/var/vcap/bosh/log/current) and monit logs (/var/vcap/monit/monit.log) to what gets sent to syslog.  It doesn't appear that is possible today unless agent and monit logs were symlinked into /var/vcap/sys/log?

**Comment by anEXPer** [comment]
Sorry it's taken us a while to look at this, thanks for the issue.

We think we'd like to follow these logs. It might be easy to just add them to the paths blackbox cares about, but symlinking them is a not-terrible idea that would get us proper app naming for free, which we'd otherwise have to figure out how to resolve. We're discussing it with the bosh team.

Do you just want these logs, or do you think the general "arbitrary source dir" feature is necessary?

**Comment by cppforlife** [comment]
@youngm what's your use case for forwarding those files? monit.log i guess may be useful for debugging some start/stop information, however, agent log is very unlikely to be useful in most cases.

**Comment by youngm** [comment]
Thanks @anEXPer today those are the only logs I wanted to add to my drain.  I think if bosh chose to symlink or move those logs into /var/vcap/sys so blackbox can pick them up then that would be a perfectly acceptable to me.

**Comment by youngm** [comment]
Hi @cppforlife I don't have any really strong use cases for `agent.log`  In the past when debugging various problems we found ourselves wanting to inspect the `agent.log` to see what the agent was doing and perhaps give us some hint to the problem we're looking into.  That said, I cannot recall any issues we've run into where `agent.log` helped find a specific problem.  But, I do recall being frequently frustrated that `agent.log` had rolled so we couldn't inspect it if we wanted to.

Anyway, wanting to drain `agent.log` is more of a "it could come in handy" type of thing so why not?  But if there are issues with draining `agent.log` I won't fight not being able to get it.

**Comment by anEXPer** [comment]
We don't currently really have a reasonable articulable philosophy for what logs should and shouldn't be forwarded. We're forwarding kernel and audit logs, and job logs; up until these two, there wasn't actually a source of logs on the system that I was explicitly aware we _weren't_ forwarding.

So to the extent we have an implicit philosophy, it's kind of maximalist: "forward everything that normal linux stuff sends to syslog, plus everything written down in the log-place by bosh." Monit and the agent fall outside our current implementation of that structure, but there's no clear reason to me that they should, and it seems like if they log at all, well, they're part of the system and our revealed design goal of "forward everything" seems like it would encompass them.

Not that "forward everything that looks like a log" is the right design goal necessarily, but it's a good place to be able to ratchet back from with custom rules and configuration. We forward lots of stuff that's probably never useful as it is.

Is there a particular volume or content concern with the agent log in particular? We didn't see anything alarming when we briefly inspected it, but we were not thorough.

**Comment by anEXPer** [comment]
We're playing around with this and man, that agent logs... all the properties for everything deployed every thirty seconds? So we've developed our own volume concerns around this. Sill interested in other information, but we're leaning towards not forwarding agent logs.

**Comment by anEXPer** [comment]
We've investigated this some more, and other things occasionally create/log to `/var/vcap/sys/log/monit`; our first thought was to symlink to there.

We're coming back around to thinking maybe custom watch-path support would be a reasonable way to enable this, though you'd be constrained by permissions if we were to implement it in rsyslog or capabilities-dropped blackbox, which is definitely the direction we're wanting to go.

At this point, I'm thinking for the monit logs in particular, we might want to ask bosh to write them to a place and permissions level we can read, rather than trying to read from where they are. @cppforlife, is this something y'all might be interested in adjusting?

**Comment by Benjamintf1** [comment]
Having investigated what's involved and the contents of these files, we're back to thinking not forwarding them is probably right for most people. However, there is a workaround if you want to forward from arbitrary files using rsyslog directly, rather than reconfiguring blackbox.

```
module(load="imfile")

input(type="imfile"
      File="/var/vcap/monit/monit.log"
      Tag="monit"
      StateFile="monit")
```

in your custom_rules section should allow you to forward logs from monit.

Please let us know if this works for you.

Also, just out of curiosity, do you find the volume of logs emitted by cloud foundry to be a problem? One of the reasons we hesitate to add to the things we're forwarding is that more of our users seem to be concerned that they are receiving too _many_ logs. You are perhaps the first to be concerned that they are receiving too few, and that's interesting.

**Comment by youngm** [comment]
@anEXPer @Benjamintf1 I think that workaround works for us.

We do think many of the CF components' logging is too verbose.  But we've worked around that issue by building a syslog proxy component that allows us manage CF component syslog output before sending it to our splunk server.  We've had so many problems with CF logging in the past that we decided a custom proxy, where we can work around logging problems ourselves, was the best approach for us.

Our proxy allows us to:
* Filter messages and components via regex.
* Properly parse all of the different date formats in events sent through syslog so that splunk will have accurate dates and event demarcation without having to use splunk config to detect the dates.
* Combine json log messages too large to fit into a single event so it will show up in splunk as a single json event.
* Combine java multi-line log message so they will show up as single splunk events.
* Rate limit and monitor logging from a given components/host so that a component that goes crazy doesn't eat up our splunk bill.
* Aggregate custom information gathered from syslog and re-publish as loggregator metrics/log messages.
* Cache events when splunk indexers are down for upgrade
* etc

Let me know if you have any other questions we're happy to share.

**Comment by Benjamintf1** [comment]
@youngm Any reason you arn't doing filtering using syslog-release? Does it have to do, with the line splitting/recombining?

**Comment by youngm** [comment]
@Benjamintf1 Yeah, we already needed some kind of proxy to do the splitting/recombining, rate limiting, setting splunk meta-data, etc.  So, we decided to just do the filtering in the proxy as well.

Another benefit of doing it in the proxy is simpler deployment config.  We could put all of our filters in one runtime config which would be simple from a config standpoint.  However, if we needed to change any filters for any jobs it would require an update of all our instance_groups including our cells.  Or we could localize the syslog-release config for every instance_group independently but that was a little harder to manage from a deployment configuration standpoint since some config is spread across instance groups and some is not.  Doing it all in one place on the proxy puts config all in one place with the added benefit of not having to update all instances_groups for a filter change.

Plus since we control the proxy we could make more complex custom filter rules if we needed too.

Make sense?

**Comment by youngm** [comment]
@Benjamintf1 Yeah, no problems with load.  We have our proxy clustered for failover.  We're using TCP so a simple DNS LB is sufficient.

**Comment by youngm** [comment]
@Benjamintf1 If you're going to be at Summit I'd be happy to chat more with you about the problems we have with system component logging and what we're doing now to work around them.  Are you doing office hours?  LMK

**Comment by anEXPer** [comment]
@youngm I'm at Summit. We don't have office hours planned, but if you drop by the syslog channel in CF slack we can definitely arrange some impromptu office hour style availability.
