### ISSUE TITLE
PCF-specific: syslog_forwarder fallbacks in Opsman UI?

### ISSUE THREAD

**Issue by aegershman** [cloudfoundry/syslog-release#44]
I know, this is a PCF-specific question, so my apologies if it's gauche to be asking in on the OSS syslog-release, _but_

in the documented `syslog-release` configuration property block (https://github.com/cloudfoundry/syslog-release#configure-forwarding), you can configure `fallback_servers`. 

**Is it possible to do this in the PCF opsman UI in the PAS tile?** As you can see from the PAS doc (https://docs.pivotal.io/pivotalcf/2-0/opsguide/logging-config-opsman.html#syslog-forward), the `address` is exposed, but not a specific field for any fallback servers. 

Maybe it's possible to configure fallback servers as members of a comma-separated list (`host: primaryserver, backup1, backup2`, etc.), but the doc makes no mention of it.

If anyone has any feedback on this, I really appreciate it. Obviously if this isn't the right place for this question, my apologies, just figured I'd ask.

**Comment by anEXPer** [comment]
It's not the right place, not that it's a big deal. I'd recommend asking us through Pivotal support, or if you have access to it, the #cf-syslog channel on Pivotal slack.

That said, it's not exposed in PAS, and one reason Pivotal support is your best bet is that it exposes it to the Pivotal product org as a feature request.

You... probably _could_ work around this with a custom rule that reimplements the rsyslog config for fallback servers from our templates in its entirety, since the custom rule field _is_ exposed. But I'd talk with Pivotal support first.
