### ISSUE TITLE
ability to add additional parameters to the outbound syslog messages

### ISSUE THREAD

**Issue by lrstanley** [cloudfoundry/syslog-release#54]
Right now, a file is dumped `/etc/rsyslog.d/25-syslog-release-forwarding-setup.conf` which contains a custom template that conforms to the specific syslog format this package uses.. However, this makes things difficult to modify. We would like to be able to add our own fields (e.g. we have multiple different bosh clusters, and adding `env="dev"` or `env="prod"` makes our lives 1000x easier, than having to try and figure out which deployment is which, etc. We could try and create our own template, but that is very cumbersome to manage.

Can we add a field in the yaml to define some additional attributes which get tacked on via templating? You'd of course want to restrict the key to something like... `[a-zA-Z_]{2,20}`, and the value to alphanumeric, with spaces, maybe? Something that doesn't collide with the existing metacharacters.

**Comment by anEXPer** [comment]
There is a currently-configurable `director` field for this purpose. It can be set using the [`syslog.director`](https://github.com/cloudfoundry/syslog-release/blob/1ad449483bd8d66b57f5ed1944b697d6daa9d62b/jobs/syslog_forwarder/spec#L27) property. Does this do what you need?

As for the larger question of self-service fields, the feature you're suggesting sets off a lot of complexity alarms to me; I'd want to accumulate a fair amount of evidence for use-cases before even inviting PRs for something like that. It's also the kind of feature that tends to mask missing features and reduce feedback, since it "can" "solve" so many "problems" and there's no way to close the loop on what people end up needing it for.

**Comment by lrstanley** [comment]
I'm not at my computer, so I'm sorry if my response is lacking. Adding
additional "fields" is a very common supported feature of any log-sending
utility. This includes rsyslog itself (e.g. json). Custom fields are
supported by things like the splunk forwarder, and filebeat (ELK stack). It
seems like a reasonable request to want to include metadata, especially
when you want to go cloud, where the source machines are generated and not
pre-setup. Knowing what datacenter, AZ, vlan (or some form of identifiable
zone), environment, what automated utility deployed the given config,
software version something is running with, using a different field than
"program" because sometimes that's not accurate, if software deploys are on
a per-team basis, know what team it's assigned to, etc. There are many
reasons why we would benefit from this across our 60 (and growing) bosh
deployments.

Putting in the bosh director hostname does not provide things like the
environent, the best thing it provides is a best-guess (and if you only
have an IP, it's useless) -- this is bad design in my opinion.

You may say, well, if you want those things, put them into the log messages
and parse them out yourself. Unfortunately, that's a flawed answer, because
you may want logs from something you didn't create, and having to
implemement this metadata into every single piece of software seems very
inefficient.
