### ISSUE TITLE
bionic stemcell releases

### ISSUE THREAD

**Issue by ywei2017** [cloudfoundry/syslog-release#67]
Can you also create bionic stemcell releases? I got the following error when trying with bionic stemcell.

```
Can't use release 'syslog/11.7.6'. It references packages without source code and are not compiled against stemcell 'bosh-vsphere-esxi-ubuntu-bionic-go_agent/1.61'
```

Thanks
Yansheng

**Comment by ywei2017** [comment]
This turns out to be non-issue, since the release is not a compiled-release.

**Comment by ywei2017** [comment]
Let's keep it open, we need some resolution than closing it.

**Comment by benjaminguttmann-avtq** [comment]
@ywei2017 what does the release definition look like that you are trying to use? To me it looks like you try to use a pre-compiled version that was not compiled against the stemcell version you want to use.

What happens if you login to your director and run a command similar to the following:

```
bosh upload-release --sha1 b54206b494ba145acbc4bfe57a6b1be62aa4cd01 https://bosh.io/d/github.com/cloudfoundry/syslog-release?v=11.7.6 --fix
```

like that you upload a non pre-compiled version of the syslog-release (the --fix ensures that it gets really re-uploaded)

**Comment by ywei2017** [comment]
@benjaminguttmann-avtq. Your suspicion right. I was using a precompiled release, instead of the source. Et e see whether I can adjust our pipeline to use the source release. 

Thanks
